name: Deploy to dev
on:
  push:
    branch:
       - "production"

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything on dev cluster

    steps:
      -name: SSH into server
      -run: |
        mkdir -p /home/runner/.ssh
        ls /home/runner/.ssh
        touch /home/runner/.ssh/known_hosts
        echo "${{ secrets.KNOWN_HOSTS }}" &> /home/runner/.ssh/known_hosts
        chmod 700 /home/runner/ssh_key
        ssh -i ~/ssh_key ubuntu@13.232.34.81 -t "cd week-25-ci-next-app/ && git pull origin main && export PATH=/root/.nvm/versions/node/v22.13.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin && npm install -g pnpm && pnpm install && pnpm run build && pm2 restart fe-sever && pm2 restart http-sever && pm2 restart ws-sever"
        
    
