name: Deploy to dev
on:
  push:
    branch:
       - "main"

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything on dev cluster

    steps:
      - run: |
          echo "${{secrets.SSH_PRIVATE_KEY}}" &> ~/ssh_key
          # mkdir -p /home/runner/.ssh
          # ls /home/runner/.ssh
          # touch /home/runner/.ssh/known_hosts
          # echo "${{ secrets.KNOWN_HOSTS }}" &> /home/runner/.ssh/known_hosts
          chmod 700 /home/runner/ssh_key
          ssh -i ~/ssh_key ubuntu@15.206.205.116 | echo "yes" -t "cd deployMonorepo && git pull origin main && pnpm install && pnpm run build && pm2 restart http-server && pm2 restart web-prod && pm2 restart web-socket-server"
    