name: Deploy to dev
on:
  push:
    branch:
       - "production"

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything on dev cluster

    name: SSH into server
    steps:
      -run: |
        ssh -i ${{secrets.SSH_PRIVATE_KEY}} ubuntu@13.232.34.81
        cd deployMonorepo && git pull
        pnpm install
        pnpm run build
        pm2 restart http-server
        pm2 restart web-prod
        pm2 restart web-socket-server
    
